### ISSUE TITLE
Error from ppp_datamodel: KeyError: 'value'

### ISSUE THREAD

**Issue by yhamoudi** [ProjetPP/PPP-QuestionParsing-Grammatical#125]
I obtain the following errors on:
```bash
python3 demo7.py
What country made the Statue of Liberty?
```

```bash
Traceback (most recent call last):
  File "demo7.py", line 20, in <module>
    print_responses(getAnswer())
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_cli-0.2-py3.4.egg/ppp_cli/dot.py", line 44, in print_responses
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_cli-0.2-py3.4.egg/ppp_cli/dot.py", line 39, in print_tree
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_datamodel-0.6.7-py3.4.egg/ppp_datamodel/nodes/list_operators.py", line 64, in traverse
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_datamodel-0.6.7-py3.4.egg/ppp_datamodel/nodes/list_operators.py", line 64, in <listcomp>
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_datamodel-0.6.7-py3.4.egg/ppp_datamodel/nodes/abstractnode.py", line 159, in traverse
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_datamodel-0.6.7-py3.4.egg/ppp_datamodel/nodes/abstractnode.py", line 160, in <dictcomp>
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_datamodel-0.6.7-py3.4.egg/ppp_datamodel/nodes/abstractnode.py", line 155, in wrapper
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_datamodel-0.6.7-py3.4.egg/ppp_datamodel/nodes/list.py", line 37, in traverse
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_datamodel-0.6.7-py3.4.egg/ppp_datamodel/nodes/list.py", line 37, in <listcomp>
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_datamodel-0.6.7-py3.4.egg/ppp_datamodel/nodes/abstractnode.py", line 161, in traverse
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_datamodel-0.6.7-py3.4.egg/ppp_datamodel/nodes/abstractnode.py", line 25, in __init__
  File "/home/yassine/.local/lib/python3.4/site-packages/ppp_datamodel-0.6.7-py3.4.egg/ppp_datamodel/nodes/resource.py", line 43, in _check_attributes
KeyError: 'value'
```

I didn't succeeded to solve this :(

**Comment by Ezibenroc** [comment]
The issue come from the datamodel: https://github.com/ProjetPP/PPP-datamodel-Python/issues/39
